providers:
  tokfm:
    categories-url: https://audycje.tokfm.pl/audycje-tokfm
    podcasts-url: https://audycje.tokfm.pl/gets
logging:
  file: data/log/application.log
  level:
    root: INFO

player:
  path: C:\Program Files\VideoLAN\VLC\vlc.exe
